# Generated by Django 4.2.10 on 2024-02-28 01:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("recommender_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
