# Generated by Django 4.2.11 on 2024-03-08 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_movie_rating_average_movie_rating_count_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="rating_average",
            new_name="ratings_average",
        ),
        migrations.RenameField(
            model_name="movie",
            old_name="rating_count",
            new_name="ratings_count",
        ),
    ]
