# Generated by Django 4.2.11 on 2024-03-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_rename_rating_average_movie_ratings_average_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="source_id",
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
